# Generated by Django 3.2.12 on 2022-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=1)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('task', models.CharField(choices=[('Make sandwich', 'Make sandwich'), ('Serve sandwich', 'Serve sandwich')], default='Make sandwich', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
